[workspace]
channels = ["conda-forge", "https://prefix.dev/robostack-noetic", "https://prefix.dev/conda-forge"]
name = "overhead-camera"
platforms = ["linux-aarch64"]
version = "0.1.0"

[tasks]
start = "roslaunch ./usb_cam.launch"

[dependencies]
#python = "3.12.*"
ros-noetic-usb-cam = ">=0.3.7,<0.4"
ros-noetic-roslaunch = ">=1.17.4,<2"
ros-noetic-image-transport-plugins = ">=1.15.0,<2"

[activation]
scripts = ["env.sh"]
